/**
 * Consent agreement rendered fully in the frontend.
 *
 * Replaces the previous `<iframe src={pdfUrl}>` view. The PDF on the
 * backend (consentPdf.service.js) is still authoritative for archival,
 * but in-page rendering is friendlier on mobile (where iOS Safari's
 * inline PDF viewer is a black box) and lets admins copy / search the
 * text.
 *
 * Both `user` and `consent` come from the admin-details endpoint —
 * shape mirrors the PDF builder's `{ user, consent }` arguments so
 * the two stay easy to keep in sync.
 *
 * Props:
 *   user    — { _id, username, email }
 *   consent — { fullName, signature, acceptedAt, version, ip }
 *   className — optional outer wrapper class
 */
export default function ConsentDocument({ user = {}, consent = {}, className = '' }) {
  const acceptedISO = consent.acceptedAt ? new Date(consent.acceptedAt) : null;
  const acceptedHuman = acceptedISO
    ? acceptedISO.toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
    : '—';
  const acceptedFull = acceptedISO ? acceptedISO.toUTCString() : '—';

  return (
    <article
      className={`bg-white text-neutral-900 ${className}`}
      // Inline letter-press feel — leaves text crisp at any zoom and
      // matches the PDF's neutral document tone.
      style={{ fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif' }}
    >
      {/* Header */}
      <header className="px-5 sm:px-8 pt-6 pb-4 border-b border-neutral-200">
        <h1 className="text-lg sm:text-xl font-bold tracking-tight">
          callnade — User Consent &amp; Community Guidelines
        </h1>
        <dl className="mt-2 grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-0.5 text-[12px] text-neutral-600">
          <Meta label="Document version">{consent.version || '—'}</Meta>
          <Meta label="Accepted at">{acceptedFull}</Meta>
          <Meta label="Account">
            {user.username ? `@${user.username}` : '—'}
            {user.email ? <span className="text-neutral-500"> · {user.email}</span> : null}
          </Meta>
          <Meta label="User ID">
            <span className="font-mono break-all">{user._id || '—'}</span>
          </Meta>
          {consent.ip && (
            <Meta label="Recorded IP">
              <span className="font-mono">{consent.ip}</span>
            </Meta>
          )}
        </dl>
      </header>

      {/* Body — 12 numbered terms */}
      <div className="px-5 sm:px-8 py-5 space-y-4 text-[13px] leading-relaxed text-neutral-700">
        {TERMS.map(([heading, body]) => (
          <section key={heading}>
            <h2 className="text-[13px] font-bold text-neutral-900 mb-1">{heading}</h2>
            <p className="text-justify">{body}</p>
          </section>
        ))}
      </div>

      {/* Declaration block — visual page break that's just a divider in
          web flow (the PDF actually starts a new page here). */}
      <div className="px-5 sm:px-8 py-5 border-t border-neutral-200 bg-neutral-50/60">
        <h2 className="text-base font-bold tracking-tight">User Declaration</h2>
        <p className="mt-1 text-[12px] text-neutral-500">
          The following declarations were checked and confirmed by the user at the
          time of registration:
        </p>

        <ul className="mt-4 space-y-2">
          {DECLARATIONS.map((d) => (
            <li key={d} className="flex items-start gap-2 text-[13px] text-neutral-800">
              <span className="text-emerald-600 font-bold tabular-nums">[x]</span>
              <span>{d}</span>
            </li>
          ))}
        </ul>

        <h3 className="mt-7 text-sm font-bold tracking-tight">Identification</h3>
        <div className="mt-2 grid grid-cols-1 sm:grid-cols-[8rem_1fr] gap-x-3 gap-y-1.5 text-[13px]">
          <span className="text-neutral-500">Full name</span>
          <span className="font-semibold">{consent.fullName || '—'}</span>
          <span className="text-neutral-500">Date</span>
          <span>{acceptedHuman}</span>
        </div>

        <div className="mt-7">
          <p className="text-sm font-bold tracking-tight mb-2">Signature</p>
          <p
            className="text-2xl text-neutral-900"
            style={{ fontFamily: 'cursive' }}
          >
            {consent.signature || '—'}
          </p>
          <div className="mt-1 h-px w-full max-w-md bg-neutral-300" />
        </div>
      </div>

      {/* Footer */}
      <footer className="px-5 sm:px-8 py-4 border-t border-neutral-200 text-center text-[11px] text-neutral-500">
        Generated by callnade. Captured electronically at the time of account
        creation. This record is retained for compliance and audit purposes.
      </footer>
    </article>
  );
}

function Meta({ label, children }) {
  return (
    <div className="flex flex-wrap items-baseline gap-1.5 min-w-0">
      <dt className="text-[10px] font-bold uppercase tracking-wide text-neutral-500 shrink-0">
        {label}
      </dt>
      <dd className="text-[12px] text-neutral-700 truncate min-w-0">{children}</dd>
    </div>
  );
}

// Mirrors the canonical list in backend/src/services/consentPdf.service.js.
// Kept inline so this module is self-contained — if the legal text needs to
// change, update both sides of the wire (frontend + backend) together.
const TERMS = [
  ['1. Eligibility Requirements',
    'By using this platform you confirm that you are at least 18 years old, are legally permitted to use online social and communication platforms in your country or region, that all information provided during registration is accurate and truthful, and that you will not impersonate another person or create fake identities for fraudulent or harmful purposes. The platform reserves the right to suspend or permanently terminate accounts suspected of violating age or identity requirements.'],
  ['2. User Responsibility',
    'You are fully responsible for: all content you upload, share, transmit, or display; your conversations, interactions, and behavior with other users; any media, messages, or communications exchanged through the platform; and protecting your account credentials and login information. The platform does not guarantee the identity, honesty, intentions, or conduct of any user. Users interact with others at their own risk.'],
  ['3. Consent to Interaction',
    'By accepting a follow request or initiating communication, you voluntarily consent to interact with another user. Profile access, image visibility, and communication features may become available after mutual acceptance. Accepting a connection does not create any obligation for further communication, personal meetings, or continued interaction. You may block or remove connections at any time.'],
  ['4. Video Calling Consent',
    'The platform may provide private video calling functionality between mutually connected users. Participation is fully voluntary. You are solely responsible for your conduct during calls and will not engage in harassment, threats, exploitation, coercion, blackmail, or illegal activity. Online interactions involve inherent risks. The platform does not actively monitor private calls in real time unless legally required or necessary for safety investigations.'],
  ['5. Prohibited Content & Conduct',
    'Strictly prohibited: any content involving minors or individuals under 18; exploitative, abusive, violent, or criminal material; human trafficking, coercion, or non-consensual activity; threats, intimidation, hate speech, stalking, blackmail, or harassment; recording video calls without explicit consent; sharing private images or conversations without permission; publishing another user\u2019s personal information; catfishing, impersonation, scam activity, or financial fraud. Violations may result in immediate suspension, permanent bans, or reporting to law enforcement.'],
  ['6. Content Ownership & License',
    'You retain ownership of the content you upload. By uploading, you grant the platform a limited, non-exclusive license to store, process, display, optimize, and moderate your content solely for operating and improving the service. You must have the legal right to upload any content you share.'],
  ['7. Privacy & Data Usage',
    'The platform may collect and process account info, uploaded media, device and usage data, and interaction records. This may be used for security, fraud prevention, moderation, platform functionality, and legal compliance.'],
  ['8. Reporting & Moderation',
    'Users may report abuse, harassment, illegal content, fake profiles, or safety concerns. The platform reserves the right to review and remove content, restrict features, suspend or terminate accounts, and cooperate with legal authorities.'],
  ['9. No Guarantee of Safety',
    'Online interactions carry inherent risks. The platform cannot guarantee the behavior or intentions of other users. Users are responsible for exercising judgment and caution.'],
  ['10. Limitation of Liability',
    'To the maximum extent permitted by law, the platform shall not be liable for user-generated content, user conduct, private interactions, damages arising from communications between users, or losses resulting from misuse of the platform.'],
  ['11. Account Suspension & Termination',
    'The platform may suspend or terminate accounts without prior notice for violations, illegal activity, abuse, security risks, or attempts to bypass moderation.'],
  ['12. Changes to Terms',
    'The platform may update these terms at any time. Continued use constitutes acceptance of revised terms.'],
];

const DECLARATIONS = [
  'I confirm that I am at least 18 years old.',
  'I understand that I am solely responsible for my interactions and conduct on the platform.',
  'I agree to comply with all platform rules and applicable laws.',
  'I consent to the platform\u2019s privacy, moderation, and safety policies.',
];
